unstable_features = true

edition = "2018"
condense_wildcard_suffixes = true
hard_tabs = false
tab_spaces = 4
wrap_comments = false
format_code_in_doc_comments = true
newline_style = "Unix"
use_small_heuristics = "Default"
indent_style = "Block"
comment_width = 80
max_width = 140
normalize_comments = true
normalize_doc_attributes = true
enum_discrim_align_threshold = 10
fn_single_line = false
force_explicit_abi = true
merge_derives = true
imports_indent = "Block"
imports_layout = "Mixed"
imports_granularity = "Module"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
struct_field_align_threshold = 10
struct_lit_single_line = false
use_field_init_shorthand = true
use_try_shorthand = true

license_template_path = ""
